# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\mubu.login.har

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from httprunner import Parameters
import pytest
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from testcases.login_test import (
    TestCaseMubuLogin as MubuLogin,
)

class TestCaseMubu(HttpRunner):

    @pytest.mark.parametrize("param", Parameters({"docTitle": "${gen_doc_title(3)}"}))
    def test_start(self, param):
        super().test_start(param)

    config = Config("testcase description")\
        .variables(
        **{"memberId":"${get_member_id()}",
            "host":"mubu.com",
            "phone":"18537810265",
            "password":"123456"}) \
            .base_url("https://$host") \
            .verify(False)\
            .export("docTitle","docID")

    teststeps = [
        Step(
                RunTestCase("Login").call(MubuLogin).export("data_unique_id","JwtToken")
            ),

        Step(
            RunRequest("/v3/api/list/create_doc")
            .options("https://api2.$host/v3/api/list/create_doc")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.$host/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "25",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "x-request-id": "c73f53f2-a3f2-413d-b85d-a9c2531db2f7",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            .extract()
            .with_jmespath("body.data.id","docID")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.$host/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "x-request-id": "fe483199-8951-4d62-ab09-bd31648a7c38",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .options("https://api2.$host/v3/api/user/current_level")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .options("https://api2.$host/v3/api/document/edit/get")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.$host/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "37",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "x-request-id": "38958548-3e03-4970-b3c0-564b1dba5160",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "${docID}", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.$host/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "x-request-id": "56d66a1d-33d3-403d-90d2-33314294ae7d",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "${docID}"})
            .extract()
            .with_jmespath("body.data.id", "userId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .options("https://api2.$host/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .options("https://api2.$host/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.$host/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "x-request-id": "1dfdb617-d5a5-455e-96cc-b8c4065ae95a",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.$host/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "x-request-id": "2baf8a20-635b-448d-b63a-7f986105c09d",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.$host/v3/api/colla/members")
            .with_params(
                **{"memberId": "${memberId}", "documentId": "${docID}"}
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.$host/v3/api/colla/members")
            .with_params(
                **{"memberId": "${memberId}", "documentId": "${docID}"}
            )
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "members:${memberId}:1606459470338",
                    "x-request-id": "1c8ec030-0684-49c4-b584-11a9c15c3316",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .options("https://api2.$host/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,member-id,request-id,version,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.$host/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "516",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:3",
                    "x-request-id": "85cd30f9-e786-4904-a3e9-57a52fb672f0",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:${userId}:${memberId}:3",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 0,
                            "content": [
                                # {"name": "nameChanged", "title": "d", "original": ""},
                                # {"name": "nameChanged", "title": "de", "original": "d"},
                                # {
                                #     "name": "nameChanged",
                                #     "title": "dem",
                                #     "original": "de",
                                # },
                                {
                                    "name": "nameChanged",
                                    "title": "${get_random_title()}",
                                    "original": "dem",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.285",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.$host/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "461",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:5",
                    "x-request-id": "d370548b-6067-4e8f-836c-4a7b491a95b9",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:${userId}:${memberId}:5",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 1,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "LHCP08kVbt",
                                                "text": "",
                                                "modified": 1606459473658,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.285",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.$host/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "508",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:7",
                    "x-request-id": "07095b5a-c5e5-437f-ad4a-e7d20595bef5",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:${userId}:${memberId}:7",
                    "token": "${docID}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docID}",
                            "version": 2,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "LHCP08kVbt",
                                                "text": "<span>hello</span>",
                                                "modified": 1606459475428,
                                            },
                                            "original": {
                                                "id": "LHCP08kVbt",
                                                "text": "",
                                                "modified": 1606459473658,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.285",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.$host/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "x-request-id": "db62dc6e-0655-4791-b3c1-63ea4c089d7b",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.$host/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "230",
                    "sec-ch-ua": '"Google Chrome";v="87", "\\"Not;A\\\\Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
                    "data-unique-id": "f308e850-307b-11eb-9ba2-e11c5edd828e",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "${JwtToken}",
                    "request-id": "MESSAGE:${userId}:${memberId}:11",
                    "x-request-id": "daa5f3f4-94fa-43a4-9937-5b339787c61e",
                    "version": "3.0.0",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 11,
                    "requestId": "MESSAGE:${userId}:${memberId}:11",
                    "token": "${docID}",
                    "data": {},
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.285",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
